//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using PackageManager.ViewModels;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Package {
    
    private PackageString[] stringsField;
    
    private PackageGeneral generalField;
    
    private string targetDirectoryDefinitionsField;
    
    private PackageComponents componentsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("String", IsNullable=false)]
    public PackageString[] Strings {
        get {
            return this.stringsField;
        }
        set {
            this.stringsField = value;
        }
    }
    
    /// <remarks/>
    public PackageGeneral General {
        get {
            return this.generalField;
        }
        set {
            this.generalField = value;
        }
    }
    
    /// <remarks/>
    public string TargetDirectoryDefinitions {
        get {
            return this.targetDirectoryDefinitionsField;
        }
        set {
            this.targetDirectoryDefinitionsField = value;
        }
    }
    
    /// <remarks/>
    public PackageComponents Components {
        get {
            return this.componentsField;
        }
        set {
            this.componentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PackageString {
    
    private string neutralField;
    
    private PackageStringLocalized[] localizedField;
    
    private string idField;
    
    /// <remarks/>
    public string Neutral {
        get {
            return this.neutralField;
        }
        set {
            this.neutralField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Localized")]
    public PackageStringLocalized[] Localized {
        get {
            return this.localizedField;
        }
        set {
            this.localizedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PackageStringLocalized {
    
    private string cultureField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Culture {
        get {
            return this.cultureField;
        }
        set {
            this.cultureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PackageGeneral : ViewModelBase {
    
    private string idField;
    
    private string versionField;
    
    private string nameField;
    
    private string vendorField;
    
    private string copyrightField;
    
    private string descriptionField;
    
    private string iconField;
    
    private string hTMLField;
    
    private string licenseAgreementField;
    
    private string requiredInstallerVersionField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
            OnPropertyChanged("Version");
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Vendor {
        get {
            return this.vendorField;
        }
        set {
            this.vendorField = value;
        }
    }
    
    /// <remarks/>
    public string Copyright {
        get {
            return this.copyrightField;
        }
        set {
            this.copyrightField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string Icon {
        get {
            return this.iconField;
        }
        set {
            this.iconField = value;
        }
    }
    
    /// <remarks/>
    public string HTML {
        get {
            return this.hTMLField;
        }
        set {
            this.hTMLField = value;
        }
    }
    
    /// <remarks/>
    public string LicenseAgreement {
        get {
            return this.licenseAgreementField;
        }
        set {
            this.licenseAgreementField = value;
        }
    }
    
    /// <remarks/>
    public string RequiredInstallerVersion {
        get {
            return this.requiredInstallerVersionField;
        }
        set {
            this.requiredInstallerVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PackageComponents {
    
    private PackageComponentsComponent componentField;
    
    /// <remarks/>
    public PackageComponentsComponent Component {
        get {
            return this.componentField;
        }
        set {
            this.componentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PackageComponentsComponent {
    
    private PackageComponentsComponentGeneral generalField;
    
    private PackageComponentsComponentItems itemsField;
    
    private PackageComponentsComponentDependenciesMinimumPlugInVersion[] dependenciesField;
    
    /// <remarks/>
    public PackageComponentsComponentGeneral General {
        get {
            return this.generalField;
        }
        set {
            this.generalField = value;
        }
    }
    
    /// <remarks/>
    public PackageComponentsComponentItems Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
        
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("MinimumPlugInVersion", typeof(PackageComponentsComponentDependenciesMinimumPlugInVersion), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public PackageComponentsComponentDependenciesMinimumPlugInVersion[] Dependencies {
        get {
            return this.dependenciesField;
        }
        set {
            this.dependenciesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PackageComponentsComponentGeneral {
    
    private byte idField;
    
    private string nameField;
    
    private string descriptionField;
    
    private bool selectableField;
    
    private bool selectedByDefaultField;
    
    /// <remarks/>
    public byte Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public bool Selectable {
        get {
            return this.selectableField;
        }
        set {
            this.selectableField = value;
        }
    }
    
    /// <remarks/>
    public bool SelectedByDefault {
        get {
            return this.selectedByDefaultField;
        }
        set {
            this.selectedByDefaultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PackageComponentsComponentItems {
    
    private PackageComponentsComponentItemsDeviceDescription[] deviceDescriptionField;

    private PackageComponentsComponentItemsFile[] fileField;

    private PackageComponentsComponentItemsFolder[] folderField;

    private PackageComponentsComponentItemsLibrary[] libraryField;
    
    private PackageComponentsComponentItemsPlugIn[] plugInField;
    
    private PackageComponentsComponentItemsOnlineHelpFile[] onlineHelpFileField;
    
    private PackageComponentsComponentItemsProfileChange[] profileChangeField;
    
    private PackageComponentsComponentItemsAddMenuCommand[] addMenuCommandField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DeviceDescription")]
    public PackageComponentsComponentItemsDeviceDescription[] DeviceDescription {
        get {
            return this.deviceDescriptionField;
        }
        set {
            this.deviceDescriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Folder")]
    public PackageComponentsComponentItemsFolder[] Folder
    {
        get
        {
            return this.folderField;
        }
        set
        {
            this.folderField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("File")]
    public PackageComponentsComponentItemsFile[] File {
        get {
            return this.fileField;
        }
        set {
            this.fileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Library")]
    public PackageComponentsComponentItemsLibrary[] Library {
        get {
            return this.libraryField;
        }
        set {
            this.libraryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PlugIn")]
    public PackageComponentsComponentItemsPlugIn[] PlugIn {
        get {
            return this.plugInField;
        }
        set {
            this.plugInField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OnlineHelpFile")]
    public PackageComponentsComponentItemsOnlineHelpFile[] OnlineHelpFile {
        get {
            return this.onlineHelpFileField;
        }
        set {
            this.onlineHelpFileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ProfileChange")]
    public PackageComponentsComponentItemsProfileChange[] ProfileChange {
        get {
            return this.profileChangeField;
        }
        set {
            this.profileChangeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddMenuCommand")]
    public PackageComponentsComponentItemsAddMenuCommand[] AddMenuCommand {
        get {
            return this.addMenuCommandField;
        }
        set {
            this.addMenuCommandField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PackageComponentsComponentItemsDeviceDescription {
    
    private string pathField;
    
    /// <remarks/>
    public string Path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
}
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class PackageComponentsComponentItemsFolder
{

    private string targetFolderField;

    private string pathField;

    /// <remarks/>
    public string TargetFolder
    {
        get
        {
            return this.targetFolderField;
        }
        set
        {
            this.targetFolderField = value;
        }
    }

    /// <remarks/>
    public string Path
    {
        get
        {
            return this.pathField;
        }
        set
        {
            this.pathField = value;
        }
    }
}



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PackageComponentsComponentItemsFile {
    
    private string targetFolderField;
    
    private string pathField;
    
    /// <remarks/>
    public string TargetFolder {
        get {
            return this.targetFolderField;
        }
        set {
            this.targetFolderField = value;
        }
    }
    
    /// <remarks/>
    public string Path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PackageComponentsComponentItemsLibrary {
    
    private string pathField;
    
    /// <remarks/>
    public string Path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PackageComponentsComponentItemsPlugIn {
    
    private string pathField;
    
    /// <remarks/>
    public string Path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PackageComponentsComponentItemsOnlineHelpFile {
    
    private string cultureField;
    
    private string pathField;
    
    /// <remarks/>
    public string Culture {
        get {
            return this.cultureField;
        }
        set {
            this.cultureField = value;
        }
    }
    
    /// <remarks/>
    public string Path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PackageComponentsComponentItemsProfileChange {
    
    private string plugInField;
    
    private string versionField;
    
    /// <remarks/>
    public string PlugIn {
        get {
            return this.plugInField;
        }
        set {
            this.plugInField = value;
        }
    }
    
    /// <remarks/>
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PackageComponentsComponentItemsAddMenuCommand {
    
    private string commandField;
    
    private string insertionPathField;
    
    private PackageComponentsComponentItemsAddMenuCommandInsertionPosition insertionPositionField;
    
    /// <remarks/>
    public string Command {
        get {
            return this.commandField;
        }
        set {
            this.commandField = value;
        }
    }
    
    /// <remarks/>
    public string InsertionPath {
        get {
            return this.insertionPathField;
        }
        set {
            this.insertionPathField = value;
        }
    }
    
    /// <remarks/>
    public PackageComponentsComponentItemsAddMenuCommandInsertionPosition InsertionPosition {
        get {
            return this.insertionPositionField;
        }
        set {
            this.insertionPositionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PackageComponentsComponentItemsAddMenuCommandInsertionPosition {
    
    private string whereField;
    
    private string commandField;
    
    /// <remarks/>
    public string Where {
        get {
            return this.whereField;
        }
        set {
            this.whereField = value;
        }
    }
    
    /// <remarks/>
    public string Command {
        get {
            return this.commandField;
        }
        set {
            this.commandField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PackageComponentsComponentDependenciesMinimumPlugInVersion {
    
    private string plugInField;
    
    private string versionField;
    
    private string annotationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PlugIn {
        get {
            return this.plugInField;
        }
        set {
            this.plugInField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Annotation {
        get {
            return this.annotationField;
        }
        set {
            this.annotationField = value;
        }
    }
}