//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ProjectTemplate {
    
    private ProjectTemplateName nameField;
    
    private ProjectTemplateFolder folderField;
    
    private ProjectTemplateDescription descriptionField;
    
    private ProjectTemplateDefaultFileName defaultFileNameField;
    
    private string templatePathField;
    
    /// <remarks/>
    public ProjectTemplateName Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public ProjectTemplateFolder Folder {
        get {
            return this.folderField;
        }
        set {
            this.folderField = value;
        }
    }
    
    /// <remarks/>
    public ProjectTemplateDescription Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public ProjectTemplateDefaultFileName DefaultFileName {
        get {
            return this.defaultFileNameField;
        }
        set {
            this.defaultFileNameField = value;
        }
    }
    
    /// <remarks/>
    public string TemplatePath {
        get {
            return this.templatePathField;
        }
        set {
            this.templatePathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProjectTemplateName {
    
    private string defaultStringField;
    
    private ProjectTemplateNameLocalizedString localizedStringField;
    
    /// <remarks/>
    public string DefaultString {
        get {
            return this.defaultStringField;
        }
        set {
            this.defaultStringField = value;
        }
    }
    
    /// <remarks/>
    public ProjectTemplateNameLocalizedString LocalizedString {
        get {
            return this.localizedStringField;
        }
        set {
            this.localizedStringField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProjectTemplateNameLocalizedString {
    
    private string cultureField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Culture {
        get {
            return this.cultureField;
        }
        set {
            this.cultureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProjectTemplateFolder {
    
    private string defaultStringField;
    
    /// <remarks/>
    public string DefaultString {
        get {
            return this.defaultStringField;
        }
        set {
            this.defaultStringField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProjectTemplateDescription {
    
    private string defaultStringField;
    
    /// <remarks/>
    public string DefaultString {
        get {
            return this.defaultStringField;
        }
        set {
            this.defaultStringField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProjectTemplateDefaultFileName {
    
    private string defaultStringField;
    
    /// <remarks/>
    public string DefaultString {
        get {
            return this.defaultStringField;
        }
        set {
            this.defaultStringField = value;
        }
    }
}
